import { describe, expect, it } from "vitest";
import { calendarOffset, decisionOpportunities, evaluateDecisionRules, parseDecisionPolicy, readEntityWindow, type DecisionSource } from "./decision-engine.js";
import { generateCandidates, type Rule } from "./strategist.js";
const policy = () => ({ version: 1, level: "campaign", metric: "roas", operator: "gt", threshold: 3, days: 3, minPurchases: 3, minSpend: 100, changePct: 10, consecutive: false });
const rule = (): Rule => ({ id: "rule", name: "Revisada", action: "subir_presupuesto", condition: policy(), params: { review_only: true }, status: "activa", mode: "semi" });
const source = (): DecisionSource => ({ today: "2026-09-06", now: "2026-09-06T12:00:00Z", entities: [{ id: "101", name: "Campaña", level: "campaign", campaign_id: null, effective_status: "ACTIVE", daily_budget: 10000, snapshot_at: "2026-09-06T11:00:00Z" }], insights: [3, 4, 5].map(d => ({ entity_id: "101", date: `2026-09-0${d}`, spend: 100, purchases: 2, purchase_value: 400, is_closed_day: true, fetched_at: "2026-09-06T11:00:00Z" })) });
describe("motor de decisiones explícitas", () => {
  it("genera con evidencia y convierte centavos una sola vez", () => { const c = generateCandidates([rule()], source()); expect(c).toHaveLength(1); expect(c[0]).toMatchObject({ before: 100, after: 110, campaign_id: "101" }); expect(c[0]!.evidence).toContainEqual({ ref: "S", label: "Gasto de la entidad", value: 300 }); });
  it("sin datos o reglas financieras no inventa propuestas", () => { expect(generateCandidates([rule()])).toEqual([]); expect(generateCandidates([{ ...rule(), action: "bloquear_subidas" }], source())).toEqual([]); expect(generateCandidates([{ ...rule(), condition: {} }], source())).toEqual([]); });
  it.each(["inactiva", "fuera_de_vigencia"])("ignora reglas %s", state => { const r = rule(); if (state === "inactiva") r.status = "inactiva"; else r.valid_from = "2026-09-07"; expect(generateCandidates([r], source())).toEqual([]); });
  it.each(["faltante", "duplicada", "abierta", "nula", "negativa", "infinita", "antigua", "futura", "snapshot_antiguo", "sin_presupuesto", "inactiva"])("excluye evidencia %s", kind => {
    const s = source();
    if (kind === "faltante") s.insights.pop(); if (kind === "duplicada") s.insights.push({ ...s.insights[0]! }); if (kind === "abierta") s.insights[0]!.is_closed_day = false;
    if (kind === "nula") s.insights[0]!.purchases = null; if (kind === "negativa") s.insights[0]!.spend = -1; if (kind === "infinita") s.insights[0]!.purchase_value = Infinity;
    if (kind === "antigua") s.insights[0]!.fetched_at = "2026-09-01T12:00:00Z"; if (kind === "futura") s.insights[0]!.fetched_at = "2026-09-07T12:00:00Z";
    if (kind === "snapshot_antiguo") s.entities[0]!.snapshot_at = "2026-08-01T00:00:00Z"; if (kind === "sin_presupuesto") s.entities[0]!.daily_budget = null; if (kind === "inactiva") s.entities[0]!.effective_status = "PAUSED";
    expect(evaluateDecisionRules([rule()], s).candidates).toEqual([]);
  });
  it("ignora el día abierto fuera de la ventana", () => { const s = source(); s.insights.push({ ...s.insights[0]!, date: s.today, is_closed_day: false, spend: 999999 }); expect(readEntityWindow(s, "101", 3).spend).toBe(300); });
  it("distingue total de días consecutivos", () => { const s = source(); s.insights[0]!.purchase_value = 100; s.insights[1]!.purchase_value = 800; expect(generateCandidates([rule()], s)).toHaveLength(1); expect(generateCandidates([{ ...rule(), condition: { ...policy(), consecutive: true } }], s)).toEqual([]); });
  it("no compara ROAS sin gasto ni CPA sin compras", () => { const s = source(); s.insights.forEach(r => { r.spend = 0; r.purchases = 0; }); const w = readEntityWindow(s, "101", 3); expect(w.roas).toBeNull(); expect(w.cpa).toBeNull(); });
  it("rechaza una muestra insuficiente", () => expect(generateCandidates([{ ...rule(), condition: { ...policy(), minPurchases: 10 } }], source())).toEqual([]));
  it("no modifica conjuntos cuyo presupuesto pertenece a CBO", () => { const s = source(); s.entities.push({ ...s.entities[0]!, id: "102", level: "adset", campaign_id: "101" }); s.insights.push(...s.insights.map(r => ({ ...r, entity_id: "102" }))); expect(generateCandidates([{ ...rule(), condition: { ...policy(), level: "adset" } }], s)).toEqual([]); });
  it("pausa solo anuncios con gasto sin compras según umbral", () => { const s = source(); s.entities[0]!.level = "ad"; s.entities[0]!.campaign_id = "100"; s.insights.forEach(r => r.purchases = 0); const r = { ...rule(), action: "pausar_anuncio" as const, condition: { ...policy(), level: "ad", metric: "spend_without_purchases", threshold: 200, minPurchases: 0, changePct: 0 } }; expect(generateCandidates([r], s)[0]).toMatchObject({ before: "ACTIVE", after: "PAUSED" }); s.insights[0]!.purchases = 1; expect(generateCandidates([r], s)).toEqual([]); });
  it.each([{ days: 0 }, { days: 15 }, { minPurchases: 0 }, { changePct: 100 }, { threshold: Infinity }, { minSpend: -1 }, { level: "ad" }, { consecutive: "yes" }])("rechaza política inválida %j", change => expect(() => parseDecisionPolicy({ ...policy(), ...change }, "subir_presupuesto")).toThrow());
  it("no atribuye causalidad ni inventa porcentajes en oportunidades parciales", () => { const o = decisionOpportunities(source(), { target_roas: 3, breakeven_roas: 2, target_cpa: null }); expect(o[0]).toMatchObject({ kind: "observe", title: "Completar evidencia" }); expect(o[0]!.reading.complete).toBe(false); });
  it("prioriza pérdida bajo equilibrio con ventana completa", () => { const s = source(); s.insights = Array.from({ length: 7 }, (_, i) => ({ ...s.insights[0]!, date: calendarOffset(s.today, -i - 1), purchase_value: 100 })); expect(decisionOpportunities(s, { target_roas: 3, breakeven_roas: 2, target_cpa: null })[0]).toMatchObject({ kind: "protect", title: "Revisar inversión bajo equilibrio" }); });
  it("maneja cambio de mes y rechaza fechas inexistentes", () => { expect(calendarOffset("2026-09-01", -1)).toBe("2026-08-31"); expect(() => calendarOffset("2026-02-30", 0)).toThrow(); });
});
